version: '3.2'
services:
  nginx:
    build: ./nginx
    container_name: amby-nginx
    ports:
      - "80:80"
    depends_on:
      - jenkins 
      - portainer
      - rocketchat
      - phpldapadmin
    networks:
      - bridge

  ldap:
    build: ldap
    container_name: amby-ldap
    ports:
      - "389:389"
    environment:
      - SLAPD_PASSWORD=secret_password
      - SLAPD_DOMAIN=ldap.service.local
      - SLAPD_FULL_DOMAIN=dc=ldap,dc=service,dc=local
    volumes:
      - ldap-config-data:/etc/ldap
      - ldap-app-data:/var/lib/ldap
    networks:
      - bridge

  phpldapadmin:
    build: phpldapadmin
    container_name: amby-phpldapadmin
    ports:
      - "3003:80"
    environment:
      - LDAP_SERVER_HOST=ldap
    networks:
      - bridge

  portainer:
    build: portainer
    container_name: amby-portainer
    restart: always
    ports:
      - "3002:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    networks:
      - bridge
      
  jenkins:
    build: jenkins
    container_name: amby-jenkins
    user: root
    restart: always
    ports:
      - 3001:8080
      - 50000:50000
    volumes:
      - ./jenkins/home:/var/jenkins_home
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
      - TZ=Asia/Tokyo
    tty: true
    networks:
      - bridge

  db:
    build: rocket.chat/db
    container_name: amby-rocketchat-db
    restart: always
    command: --smallfiles
    volumes:
      - ./rocket.chat/db/data:/data/db
    environment:
      - TZ=Asia/Tokyo
    tty: true
    networks:
      - bridge

  rocketchat:
    build: rocket.chat/app
    container_name: amby-rocketchat
    depends_on:
      - db
    restart: always
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000/rocketchat
      - TZ=Asia/Tokyo
    tty: true
    networks:
      - bridge

networks:
  bridge:
    driver: bridge

volumes:
  ldap-config-data: {}
  ldap-app-data: {}