version: '3'
services:
  jenkins:
    build: ./jenkins
    ports:
      - 8080:8080
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      qass_ci_net:
        ipv4_address: 172.16.238.10
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

networks:
  qass_ci_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.237.0/16

volumes:
  jenkins-data:
    driver: local
